# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_DialogoOpcionesPagina.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogoOpcionesPagina(object):
    def setupUi(self, DialogoOpcionesPagina):
        DialogoOpcionesPagina.setObjectName("DialogoOpcionesPagina")
        DialogoOpcionesPagina.resize(504, 276)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogoOpcionesPagina)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelOpcionesPagina = QtWidgets.QLabel(DialogoOpcionesPagina)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOpcionesPagina.setFont(font)
        self.labelOpcionesPagina.setObjectName("labelOpcionesPagina")
        self.horizontalLayout_4.addWidget(self.labelOpcionesPagina)
        self.line_2 = QtWidgets.QFrame(DialogoOpcionesPagina)
        self.line_2.setMinimumSize(QtCore.QSize(350, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTamanno = QtWidgets.QLabel(DialogoOpcionesPagina)
        self.labelTamanno.setObjectName("labelTamanno")
        self.horizontalLayout.addWidget(self.labelTamanno)
        self.comboTamanno = QtWidgets.QComboBox(DialogoOpcionesPagina)
        self.comboTamanno.setMinimumSize(QtCore.QSize(100, 0))
        self.comboTamanno.setObjectName("comboTamanno")
        self.comboTamanno.addItem("")
        self.comboTamanno.addItem("")
        self.horizontalLayout.addWidget(self.comboTamanno)
        spacerItem = QtWidgets.QSpacerItem(13, 34, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBoxOrientacion = QtWidgets.QGroupBox(DialogoOpcionesPagina)
        self.groupBoxOrientacion.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBoxOrientacion.setObjectName("groupBoxOrientacion")
        self.radioButtonOrientacionHorizontal = QtWidgets.QRadioButton(self.groupBoxOrientacion)
        self.radioButtonOrientacionHorizontal.setGeometry(QtCore.QRect(200, 0, 90, 22))
        self.radioButtonOrientacionHorizontal.setObjectName("radioButtonOrientacionHorizontal")
        self.radioButtonOrientacionVertical = QtWidgets.QRadioButton(self.groupBoxOrientacion)
        self.radioButtonOrientacionVertical.setGeometry(QtCore.QRect(100, 0, 73, 22))
        self.radioButtonOrientacionVertical.setChecked(True)
        self.radioButtonOrientacionVertical.setObjectName("radioButtonOrientacionVertical")
        self.radioButtonOrientacionVertical.raise_()
        self.radioButtonOrientacionHorizontal.raise_()
        self.horizontalLayout.addWidget(self.groupBoxOrientacion)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelEncabezado = QtWidgets.QLabel(DialogoOpcionesPagina)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelEncabezado.setFont(font)
        self.labelEncabezado.setObjectName("labelEncabezado")
        self.horizontalLayout_5.addWidget(self.labelEncabezado)
        self.line = QtWidgets.QFrame(DialogoOpcionesPagina)
        self.line.setMinimumSize(QtCore.QSize(400, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBoxEncabezado = QtWidgets.QGroupBox(DialogoOpcionesPagina)
        self.groupBoxEncabezado.setTitle("")
        self.groupBoxEncabezado.setObjectName("groupBoxEncabezado")
        self.radioButtonEncabezadoDatos = QtWidgets.QRadioButton(self.groupBoxEncabezado)
        self.radioButtonEncabezadoDatos.setGeometry(QtCore.QRect(11, 1, 134, 22))
        self.radioButtonEncabezadoDatos.setChecked(False)
        self.radioButtonEncabezadoDatos.setObjectName("radioButtonEncabezadoDatos")
        self.radioButtonEncabezadoNo = QtWidgets.QRadioButton(self.groupBoxEncabezado)
        self.radioButtonEncabezadoNo.setGeometry(QtCore.QRect(151, 1, 48, 22))
        self.radioButtonEncabezadoNo.setChecked(True)
        self.radioButtonEncabezadoNo.setObjectName("radioButtonEncabezadoNo")
        self.radioButtonEncabezadoDefinir = QtWidgets.QRadioButton(self.groupBoxEncabezado)
        self.radioButtonEncabezadoDefinir.setGeometry(QtCore.QRect(205, 1, 70, 22))
        self.radioButtonEncabezadoDefinir.setObjectName("radioButtonEncabezadoDefinir")
        self.radioButtonEncabezadoNo.raise_()
        self.radioButtonEncabezadoDefinir.raise_()
        self.radioButtonEncabezadoDatos.raise_()
        self.verticalLayout.addWidget(self.groupBoxEncabezado)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelPie = QtWidgets.QLabel(DialogoOpcionesPagina)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPie.setFont(font)
        self.labelPie.setObjectName("labelPie")
        self.horizontalLayout_7.addWidget(self.labelPie)
        self.line_3 = QtWidgets.QFrame(DialogoOpcionesPagina)
        self.line_3.setMinimumSize(QtCore.QSize(450, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.groupBoxFecha = QtWidgets.QGroupBox(DialogoOpcionesPagina)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxFecha.setFont(font)
        self.groupBoxFecha.setObjectName("groupBoxFecha")
        self.radioButtonFechaHoy = QtWidgets.QRadioButton(self.groupBoxFecha)
        self.radioButtonFechaHoy.setGeometry(QtCore.QRect(51, 3, 55, 22))
        self.radioButtonFechaHoy.setChecked(True)
        self.radioButtonFechaHoy.setObjectName("radioButtonFechaHoy")
        self.radioButtonFechaNo = QtWidgets.QRadioButton(self.groupBoxFecha)
        self.radioButtonFechaNo.setGeometry(QtCore.QRect(112, 3, 48, 22))
        self.radioButtonFechaNo.setObjectName("radioButtonFechaNo")
        self.radioButtonFechaDefinir = QtWidgets.QRadioButton(self.groupBoxFecha)
        self.radioButtonFechaDefinir.setGeometry(QtCore.QRect(166, 3, 70, 22))
        self.radioButtonFechaDefinir.setObjectName("radioButtonFechaDefinir")
        self.pushButtonFechaPosicion = QtWidgets.QPushButton(self.groupBoxFecha)
        self.pushButtonFechaPosicion.setGeometry(QtCore.QRect(242, 1, 85, 27))
        self.pushButtonFechaPosicion.setObjectName("pushButtonFechaPosicion")
        self.verticalLayout.addWidget(self.groupBoxFecha)
        self.groupBoxNumeracion = QtWidgets.QGroupBox(DialogoOpcionesPagina)
        self.groupBoxNumeracion.setObjectName("groupBoxNumeracion")
        self.radioButtonNumeracionNo = QtWidgets.QRadioButton(self.groupBoxNumeracion)
        self.radioButtonNumeracionNo.setGeometry(QtCore.QRect(138, 3, 48, 22))
        self.radioButtonNumeracionNo.setChecked(True)
        self.radioButtonNumeracionNo.setObjectName("radioButtonNumeracionNo")
        self.pushButtonNumeracionPosicion = QtWidgets.QPushButton(self.groupBoxNumeracion)
        self.pushButtonNumeracionPosicion.setGeometry(QtCore.QRect(192, 1, 85, 27))
        self.pushButtonNumeracionPosicion.setObjectName("pushButtonNumeracionPosicion")
        self.radioButtonNumeracionSi = QtWidgets.QRadioButton(self.groupBoxNumeracion)
        self.radioButtonNumeracionSi.setGeometry(QtCore.QRect(91, 3, 41, 22))
        self.radioButtonNumeracionSi.setChecked(False)
        self.radioButtonNumeracionSi.setObjectName("radioButtonNumeracionSi")
        self.verticalLayout.addWidget(self.groupBoxNumeracion)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogoOpcionesPagina)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_8.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DialogoOpcionesPagina)
        self.buttonBox.accepted.connect(DialogoOpcionesPagina.accept)
        self.buttonBox.rejected.connect(DialogoOpcionesPagina.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogoOpcionesPagina)

    def retranslateUi(self, DialogoOpcionesPagina):
        _translate = QtCore.QCoreApplication.translate
        DialogoOpcionesPagina.setWindowTitle(_translate("DialogoOpcionesPagina", "Opciones de página"))
        self.labelOpcionesPagina.setText(_translate("DialogoOpcionesPagina", "Opciones de página:"))
        self.labelTamanno.setText(_translate("DialogoOpcionesPagina", "Tamaño:"))
        self.comboTamanno.setItemText(0, _translate("DialogoOpcionesPagina", "A4"))
        self.comboTamanno.setItemText(1, _translate("DialogoOpcionesPagina", "A3"))
        self.groupBoxOrientacion.setTitle(_translate("DialogoOpcionesPagina", "Orientación:"))
        self.radioButtonOrientacionHorizontal.setText(_translate("DialogoOpcionesPagina", "Horizontal"))
        self.radioButtonOrientacionVertical.setText(_translate("DialogoOpcionesPagina", "Vertical"))
        self.labelEncabezado.setText(_translate("DialogoOpcionesPagina", "Encabezado:"))
        self.radioButtonEncabezadoDatos.setText(_translate("DialogoOpcionesPagina", "Datos de proyecto"))
        self.radioButtonEncabezadoNo.setText(_translate("DialogoOpcionesPagina", "No"))
        self.radioButtonEncabezadoDefinir.setText(_translate("DialogoOpcionesPagina", "Definir"))
        self.labelPie.setText(_translate("DialogoOpcionesPagina", "Pie:"))
        self.groupBoxFecha.setTitle(_translate("DialogoOpcionesPagina", "Fecha:"))
        self.radioButtonFechaHoy.setText(_translate("DialogoOpcionesPagina", "Hoy"))
        self.radioButtonFechaNo.setText(_translate("DialogoOpcionesPagina", "No"))
        self.radioButtonFechaDefinir.setText(_translate("DialogoOpcionesPagina", "Definir"))
        self.pushButtonFechaPosicion.setText(_translate("DialogoOpcionesPagina", "Posición"))
        self.groupBoxNumeracion.setTitle(_translate("DialogoOpcionesPagina", "Numeración:"))
        self.radioButtonNumeracionNo.setText(_translate("DialogoOpcionesPagina", "No"))
        self.pushButtonNumeracionPosicion.setText(_translate("DialogoOpcionesPagina", "Posición"))
        self.radioButtonNumeracionSi.setText(_translate("DialogoOpcionesPagina", "Si"))

